name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: OpenCover Badge Generator
        uses: danpetitt/open-cover-badge-generator-action@v1.0.9
        with:
          path-to-opencover-xml: ./test/opencover.xml
          path-to-badges: ./
          minimum-coverage: 750
          commit-badges: false
          repo-token: ${{ secrets.CI_TOKEN }}

